module.exports = {
  LOGIN_USER: "LOGIN_USER",
  ERROR: "ERROR",
  LOGOUT: "LOGOUT",
  RECEIVE_PROJECT: "RECEIVE_PROJECT",
  PROJECT_ERROR: "PROJECT_ERROR",
  DESTROY_PROJECT: "DESTROY_PROJECT",
  RECEIVE_USERS: "RECEIVE_USERS",
  USER_ERROR: "USER_ERROR",
  CLEAR_USERS: "CLEAR_USERS",
  RECEIVE_PROJECT_AND_UDPATE: "RECEIVE_PROJECT_AND_UDPATE",
  RECEIVE_TODOS: "RECEIVE_TODOS",
  TODO_ERROR: "TODO_ERROR"
};
